### ISSUE TITLE
Getting error when running this code

### ISSUE THREAD

**Issue by lordaltair** [viromedia/ViroARSampleApp#7]
Hi, I have an issue when I'm trying to run this code. You can see the error below and it says that a file (vrx file which is a 3d Model) does not exists! but it exists in that place. I checked the code i saw that this exception is made when the program couldn't find the place of the object but the object is in that direction:
`Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module './js/res/coffee_mug/object_coffee_mug.vrx' from 'C:\Users\Ali\ReactNativeProjects\ViroMainProject - Copy\ViroARSampleApp\App.js': The module './js/res/coffee_mug/object_coffee_mug.vrx' could not be found from 'C:\Users\Ali\ReactNativeProjects\ViroMainProject - Copy\ViroARSampleApp\App.js'. Indeed, none of these files exist:   'C:\Users\Ali\ReactNativeProjects\ViroMainProject - Copy\ViroARSampleApp\js\res\coffee_mug\object_coffee_mug.vrx(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)'
  'C:\Users\Ali\ReactNativeProjects\ViroMainProject - Copy\ViroARSampleApp\js\res\coffee_mug\object_coffee_mug.vrx\index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)'`

![photo_2018-11-02_00-17-31](https://user-images.githubusercontent.com/20206984/47878965-c20b8280-de34-11e8-98ac-803c4f1c97e4.jpg)

My development OS is Windows10. The Device is Iphone7 and the iOS version is 11.3.1. ViroReact version is v2.3.0 and React Native version is 0.57.4.

**Comment by lordaltair** [comment]
Does anyone know anything? This is really important!! :)

**Comment by dam00n** [comment]
Can you check to see if “vrx” is in your rn-cli.config.js file in the project root like this:

getAssetExts() {
    return ["obj", "mtl", "JPG", "vrx", "hdr", "gltf", "glb", "bin", "arobject", "gif"];
  },

See Adding Asset Types in our docs -> https://docs.viromedia.com/docs/importing-assets

**Comment by lordaltair** [comment]
> Can you check to see if “vrx” is in your rn-cli.config.js file in the project root like this:
> 
> getAssetExts() {
> return ["obj", "mtl", "JPG", "vrx", "hdr", "gltf", "glb", "bin", "arobject", "gif"];
> },
> 
> See Adding Asset Types in our docs -> https://docs.viromedia.com/docs/importing-assets

Yeah "vrx" is in rn-cli.config.js file:

 getAssetExts() {
    return ["obj", "mtl", "JPG", "vrx"];
  },

**Comment by dam00n** [comment]
The latest version of ViroReact is 2.11. You might want to upgrade your platform version

**Comment by lordaltair** [comment]
> The latest version of ViroReact is 2.11. You might want to upgrade your platform version

ViroReact version is 2.11.0 now but the error still remains

**Comment by dthian** [comment]
Hey @lordaltair, 2 quick questions:
1) Did you follow the setup instructions for Windows at https://docs.viromedia.com/docs/quick-start-windows?
2) Viro React is only currently compatible and tested with React Native v0.55.1. If you would like to use ViroReact, please downgrade accordingly.

Thanks!

**Comment by lordaltair** [comment]
> Hey @lordaltair, 2 quick questions:
> 
> 1. Did you follow the setup instructions for Windows at https://docs.viromedia.com/docs/quick-start-windows?
> 2. Viro React is only currently compatible and tested with React Native v0.55.1. If you would like to use ViroReact, please downgrade accordingly.
> 
> Thanks!

1. Yeah, I used the instructions.
2. Downgrading the React Native to v0.55.1 fixed the problem!!! Thank You all so much!

**Comment by ajth789** [comment]
I am having exactly the same issue for Android on Windows. 

I have followed the quick start instructions and am running React Native v0.55.1 and ViroReact 2.12

Does anyone have any other suggestions?

**Comment by dam00n** [comment]
@ajth789 we just released to ViroReact 2.13 (on 1/10) and this sample was updated for that release -> https://docs.viromedia.com/docs/releases

ViroReact 2.13 is now compatible with React Native v0.57.7

**Comment by mrmub26** [comment]
Hi @dam00n , I have the same problem with this thread. but I'm using these dependencies : 
"react": "16.8.3",
"react-native": "0.59.3",
"react-viro": "2.14.0"

Do I have to downgrade to v0.55.1?

I trying to run this on IOS, for android all good. Only IOS has a problem.

Please help me. Thank you
![WhatsApp Image 2019-05-15 at 6 28 20 PM](https://user-images.githubusercontent.com/44362481/57769974-c698e800-7741-11e9-85c8-a2804cfc8f65.jpeg)

**Comment by Peege151** [comment]
Still getting this error.  Can this be updated to run with React 59.9?  All the other Viro Media apps seem to work with 59.9
